{% set version = "68.7.0esr" %}

package:
  name: firefox
  version: {{ version }}

source:
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/linux-x86_64/en-US/firefox-{{ version }}.tar.bz2  # [linux64]
  sha256: fd96ed55c53d34e033d79aa135827b584a5b16dfe3be6383fdbdd30ebadd3948  # [linux64]

  fn: firefox.pkg  # [osx]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/mac/en-US/Firefox%20{{ version }}.pkg  # [osx]
  sha256: 4c5f49dcd8f1c60f226c91d06ab382749a420e55f55cd623e7c4b2dec6d7d660  # [osx]

  fn: firefox.msi  # [win]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/win64/en-US/Firefox%20Setup%20{{ version }}.msi  # [win]
  sha256: 437ad42292ef5adc1b522a58192749d408eb0016978c3e44b24f19105494ef65  # [win]

build:
  number: 0
  binary_relocation:
    - bin/firefox

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  requires:
    - selenium
    - geckodriver

about:
  home: https://www.mozilla.org/en-US/firefox/releases
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: 'Firefox web browser'

extra:
  recipe-maintainers:
    - birdsarah
    - ocefpaf
    - bollwyvl
