{% set version = "68.8.0esr" %}

package:
  name: firefox
  version: {{ version }}

source:
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/linux-x86_64/en-US/firefox-{{ version }}.tar.bz2  # [linux64]
  sha256: 23227258d82c786395eb71de0b8726f94eb0b37d0953ad2eb125c1bd4f738f94  # [linux64]

  fn: firefox.pkg  # [osx]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/mac/en-US/Firefox%20{{ version }}.pkg  # [osx]
  sha256: 50c56bde440f1c55e336a17319c2d81668752de09c1d5ef4264f4335cba39ea0  # [osx]

  fn: firefox.msi  # [win]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/win64/en-US/Firefox%20Setup%20{{ version }}.msi  # [win]
  sha256: 8cd9b0bcab48bc9775e1c0474948b7f791ec525230dca8c59b9a79e7bdcd29f7  # [win]

build:
  number: 0
  binary_relocation:
    - bin/firefox

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  requires:
    - selenium
    - geckodriver

about:
  home: https://www.mozilla.org/en-US/firefox/releases
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: 'Firefox web browser'

extra:
  recipe-maintainers:
    - birdsarah
    - ocefpaf
    - bollwyvl
