{% set version = "77.0.1" %}

package:
  name: firefox
  version: {{ version }}

source:
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/linux-x86_64/en-US/firefox-{{ version }}.tar.bz2  # [linux64]
  sha256: 03859fd56f79cb520e30bae2433b6f61f806c8f95e7576092894eb1d644e6ff1  # [linux64]

  fn: firefox.pkg  # [osx]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/mac/en-US/Firefox%20{{ version }}.pkg  # [osx]
  sha256: 820a0bd5d0fcf07aacf3e67ea300abc4fd0cad4a173284ff80dca23d7678a082  # [osx]

  fn: firefox.msi  # [win]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/win64/en-US/Firefox%20Setup%20{{ version }}.msi  # [win]
  sha256: 14ed31f7981bf9a5855812998da286cca34416283315ee4234f9f6b00f38856a  # [win]

build:
  number: 0
  binary_relocation:
    - bin/firefox

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  requires:
    - selenium
    - geckodriver

about:
  home: https://www.mozilla.org/en-US/firefox/releases
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Firefox web browser

extra:
  recipe-maintainers:
    - birdsarah
    - ocefpaf
    - bollwyvl
