{% set version = "79.0" %}

package:
  name: firefox
  version: {{ version }}

source:
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/linux-x86_64/en-US/firefox-{{ version }}.tar.bz2  # [linux64]
  sha256: d57ce2ec9d39d4f0e1100a2faf7cfdc827eeb45db672511d5a6aea7229430f85  # [linux64]

  fn: firefox.pkg  # [osx]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/mac/en-US/Firefox%20{{ version }}.pkg  # [osx]
  sha256: a19d6c1d496215b03b9acb99f29fc7a258265095df69a2948e1782f3eaa3b855  # [osx]

  fn: firefox.msi  # [win]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/win64/en-US/Firefox%20Setup%20{{ version }}.msi  # [win]
  sha256: 732cdb321f7496c712d70b137b54073192e325ce382c46fe3dd13c1ec82034f3  # [win]

build:
  number: 1
  binary_relocation:
    - bin/firefox

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - gtk3  # [linux]
  run:
    - gtk3  # [linux]

test:
  requires:
    - selenium
    - geckodriver
    - pytest-azurepipelines
    - python >=3.6
  commands:
    - copy {{ RECIPE_DIR }}\test_selenium.py {{ RECIPE_DIR }}\setup.cfg . # [win]
    - cp {{ RECIPE_DIR }}/test_selenium.py {{ RECIPE_DIR }}/setup.cfg . # [not win]
    - python -m pytest


about:
  home: https://www.mozilla.org/en-US/firefox/releases
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: Firefox web browser

extra:
  recipe-maintainers:
    - birdsarah
    - ocefpaf
    - bollwyvl
