{% set version = "74.0.1" %}

package:
  name: firefox
  version: {{ version }}

source:
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/linux-x86_64/en-US/firefox-{{ version }}.tar.bz2  # [linux64]
  sha256: 337384041df84656c2ed31fc097fb18ca81988f801d0417bb3c628413a9c7ab1  # [linux64]

  fn: firefox.pkg  # [osx]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/mac/en-US/Firefox%20{{ version }}.pkg  # [osx]
  sha256: e2775a1f042320dae1fc4cd4f65e665f79b0dd0d4f265d25777e76a61eb220c2  # [osx]

  fn: firefox.msi  # [win]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/win64/en-US/Firefox%20Setup%20{{ version }}.msi  # [win]
  sha256: 3f429f87894800ff627e99c0f74807bc364d825a79785d90b44ec6805e7f32b8  # [win]

build:
  number: 0
  binary_relocation:
    - bin/firefox

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  requires:
    - selenium
    - geckodriver

about:
  home: https://www.mozilla.org/en-US/firefox/releases
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: 'Firefox web browser'

extra:
  recipe-maintainers:
    - birdsarah
    - ocefpaf
    - bollwyvl
